include: "boilerplate.smk"


slots = list(range(3))

rule reduce:
  input: remote(expand("transf-{slot}.pkl", slot=slots))
  output: remote("reduced.pkl")

  shell:
   "python3 job.py reduce --input {input} --output {output}"

rule produce:
  output: remote("prod-{slot}.pkl")

  shell:
   "python3 job.py produce --output {output} --config {wildcards.slot} --waited-time 1"


rule transform:
  input: remote("prod-{slot}.pkl")
  output: remote("transf-{slot}.pkl")

  shell:
   "python3 job.py transform --input {input} --output {output} --waited-time 1"


